const quotes = [
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Act as if what you do makes a difference. It does. - William James",
    "Success is getting what you want. Happiness is wanting what you get. - Dale Carnegie",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "It is not the mountain we conquer but ourselves. - Edmund Hillary",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "In a gentle way, you can shake the world. - Mahatma Gandhi",
    "It does not matter what you bear, but how you bear it. - Seneca",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "Do what you feel in your heart to be right—for you’ll be criticized anyway. - Eleanor Roosevelt",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    'Limit your "always" and your "nevers." - Amy Poehler',
    "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "We generate fears while we sit. We overcome them by action. - Dr. Henry Link",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    "Life is what happens when you’re busy making other plans. - John Lennon",
    "You get what you give. - Jennifer Lopez",
    "Dream big and dare to fail. - Norman Vaughan",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "The secret of getting ahead is getting started. - Mark Twain",
    "You can do anything, but not everything. - David Allen",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don’t raise your voice, improve your argument. - Desmond Tutu",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "Happiness is not a goal...it’s a by-product of a life well-lived. - Eleanor Roosevelt",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "If you cannot do great things, do small things in a great way. - Napoleon Hill",
    "Courage is grace under pressure. - Ernest Hemingway",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "Work hard in silence, let your success be your noise. - Frank Ocean",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "When you have a dream, you’ve got to grab it and never let go. - Carol Burnett",
    "Whether you think you can or you think you can’t, you’re right. - Henry Ford",
    "Do not fear failure but rather fear not trying. - Roy T. Bennett",
    "Your big opportunity may be right where you are now. - Napoleon Hill",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "Stay foolish to stay sane. - Maxime Lagacé",
    "When nothing goes right, go left. - Unknown",
    "Try to be a rainbow in someone’s cloud. - Maya Angelou",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Do what is right, not what is easy nor what is popular. - Roy T. Bennett",
    "Don’t wait. The time will never be just right. - Napoleon Hill",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "What lies behind us and what lies before us are small matters compared to what lies within us. - Ralph Waldo Emerson",
    "It’s not the years in your life that count. It’s the life in your years. - Abraham Lincoln",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "You define your own life. Don’t let other people write your script. - Oprah Winfrey",
    "Don’t let what you cannot do interfere with what you can do. - John Wooden",
    "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
    "Opportunities don’t happen. You create them. - Chris Grosser",
    "Keep your eyes on the stars and your feet on the ground. - Theodore Roosevelt",
    "Do not let what you cannot do interfere with what you can do. - John Wooden",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "Only those who will risk going too far can possibly find out how far one can go. - T.S. Eliot",
    "Failure is simply the opportunity to begin again, this time more intelligently. - Henry Ford",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. - Unknown",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The harder the conflict, the greater the triumph. - George Washington",
    "The best revenge is massive success. - Frank Sinatra",
    "Do not wait; the time will never be 'just right.' Start where you stand, and work with whatever tools you may have at your command. - Napoleon Hill",
    "Always do your best. What you plant now, you will harvest later. - Og Mandino",
    "To see what is right and not do it is a lack of courage. - Confucius",
    "The future depends on what you do today. - Mahatma Gandhi",
    "Keep going. Everything you need will come to you at the perfect time. - Unknown",
    "Don’t stop when you’re tired. Stop when you’re done. - Marilyn Monroe",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Doubt kills more dreams than failure ever will. - Suzy Kassem",
    "Act as if what you do makes a difference. It does. - William James",
    "With the new day comes new strength and new thoughts. - Eleanor Roosevelt",
    "Quality is not an act, it is a habit. - Aristotle",
    "Happiness depends upon ourselves. - Aristotle",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "He who is not courageous enough to take risks will accomplish nothing in life. - Muhammad Ali",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "You can, you should, and if you’re brave enough to start, you will. - Stephen King",
    "The more you praise and celebrate your life, the more there is in life to celebrate. - Oprah Winfrey",
    "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Do not let the behavior of others destroy your inner peace. - Dalai Lama",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "It is never too late to be what you might have been. - George Eliot",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "Try to be a rainbow in someone’s cloud. - Maya Angelou",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "If you want something you’ve never had, you must be willing to do something you’ve never done. - Thomas Jefferson",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "You cannot change your destination overnight, but you can change your direction overnight. - Jim Rohn",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
    "It’s not what happens to you, but how you react to it that matters. - Epictetus",
    "You must do the thing you think you cannot do. - Eleanor Roosevelt",
    "Shoot for the moon. Even if you miss, you’ll land among the stars. - Norman Vincent Peale",
    "Nothing is impossible, the word itself says, ‘I’m possible!’ - Audrey Hepburn",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Some people want it to happen, some wish it would happen, others make it happen. - Michael Jordan",
    "The most common way people give up their power is by thinking they don’t have any. - Alice Walker",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Life is what happens when you’re busy making other plans. - John Lennon",
    "It is our choices, that show what we truly are, far more than our abilities. - J.K. Rowling",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us. - Helen Keller",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
    "Don’t cry because it’s over, smile because it happened. - Dr. Seuss",
    "Happiness is not a goal...it’s a by-product of a life well-lived. - Eleanor Roosevelt",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston S. Churchill",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Keep your eyes on the stars and your feet on the ground. - Theodore Roosevelt",
    "Success is getting what you want. Happiness is wanting what you get. - Dale Carnegie",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "Don’t wait. The time will never be just right. - Napoleon Hill",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "It’s not whether you get knocked down; it’s whether you get up. - Vince Lombardi",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Act as if what you do makes a difference. It does. - William James",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Don’t let what you cannot do interfere with what you can do. - John Wooden",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "If you want something you’ve never had, you must be willing to do something you’ve never done. - Thomas Jefferson",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Success is getting what you want. Happiness is wanting what you get. - Dale Carnegie",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "It does not matter what you bear, but how you bear it. - Seneca",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "Life is short, and it is up to you to make it sweet. - Sarah Louise Delany",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "We generate fears while we sit. We overcome them by action. - Dr. Henry Link",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Dream big and dare to fail. - Norman Vaughan",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    "Life is what happens when you’re busy making other plans. - John Lennon",


    // sports quotes started
    "The only way to prove that you’re a good sport is to lose. - Ernie Banks",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Champions keep playing until they get it right. - Billie Jean King",
    "Sports do not build character. They reveal it. - Heywood Hale Broun",
    "A champion is afraid of losing. Everyone else is afraid of winning. - Billie Jean King",
    "The more difficult the victory, the greater the happiness in winning. - Pele",
    "Winning isn’t everything, but wanting to win is. - Vince Lombardi",
    "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do. - Pelé",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "If you don’t have confidence, you’ll always find a way not to win. - Carl Lewis",
    "You have to expect things of yourself before you can do them. - Michael Jordan",
    "The harder the battle, the sweeter the victory. - Les Brown",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Winning means you’re willing to go longer, work harder, and give more than anyone else. - Vince Lombardi",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "Do not let what you cannot do interfere with what you can do. - John Wooden",
    "A winner is someone who gets up one more time than they are knocked down. - Anonymous",
    "The only time to be positive you’re in the right path is when you’re on the edge. - Anonymous",
    "You have to be willing to fail in order to succeed. - Kareem Abdul-Jabbar",
    "Great things come from hard work and perseverance. No excuses. - Kobe Bryant",
    "If you aren’t going all the way, why go at all? - Joe Namath",
    "The more I practice, the luckier I get. - Gary Player",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "You’ve got to take the initiative and play your game. In a decisive set, confidence is the difference. - Chris Evert",
    "Age is no barrier. It’s a limitation you put on your mind. - Jackie Joyner-Kersee",
    "Life is 10% what happens to you and 90% how you respond to it. - Charles R. Swindoll",
    "Do your best when it’s hardest to do your best. - John Wooden",
    "Sports are a microcosm of life. - Mark Cuban",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in determination. - Vince Lombardi",
    "Success is how high you bounce when you hit bottom. - George S. Patton",
    "The secret to success is to be ready when your opportunity comes. - Benjamin Disraeli",
    "It’s not the will to win that matters—everyone has that. It’s the will to prepare to win that matters. - Paul “Bear” Bryant",
    "The road to success is dotted with many tempting parking spaces. - Will Rogers",
    "Talent is never enough. With few exceptions, the best players are the hardest workers. - Magic Johnson",
    "If you can believe it, the mind can achieve it. - Ronnie Lott",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. - Vince Lombardi",
    "I’ve failed over and over and over again in my life and that is why I succeed. - Michael Jordan",
    "You have to be able to accept failure to get better. - LeBron James",
    "Victory is sweetest when you’ve known defeat. - Malcolm S. Forbes",
    "It’s hard to beat a person who never gives up. - Babe Ruth",
    "If you want to be the best, you have to do things that other people aren’t willing to do. - Michael Phelps",
    "The key is not the will to win… everybody has that. It is the will to prepare to win that is important. - Bobby Knight",
    "The only thing you can control is your effort. - Anonymous",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. - Bruce Lee",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Hard work beats talent when talent doesn’t work hard. - Tim Notke",
    "Winning means you’re willing to go longer, work harder, and give more than anyone else. - Vince Lombardi",
    "The difference between who you are and who you want to be is what you do. - Anonymous",
    "What you lack in talent can be made up with desire, hustle, and giving 110% all the time. - Don Zimmer",
    "A person who won’t read has no advantage over one who can’t read. - Mark Twain",

    // motivational quotes started

    "The only way to do great work is to love what you do. - Steve Jobs",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "The harder you work for something, the greater you'll feel when you achieve it. - Anonymous",
    "Success doesn’t just find you. You have to go out and get it. - Anonymous",
    "Don’t stop when you’re tired. Stop when you’re done. - Anonymous",
    "Wake up with determination. Go to bed with satisfaction. - Anonymous",
    "Little things make big things happen. - John Wooden",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Act as if what you do makes a difference. It does. - William James",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The key to success is to focus on goals, not obstacles. - Anonymous",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua Marine",
    "Don’t wait for opportunity. Create it. - Anonymous",
    "Your limitation—it’s only your imagination. - Anonymous",
    "Great things never come from comfort zones. - Anonymous",
    "Dream it. Wish it. Do it. - Anonymous",
    "Success doesn’t just find you. You have to go out and get it. - Anonymous",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Anonymous",
    "Dream bigger. Do bigger. - Anonymous",
    "It’s going to be hard, but hard does not mean impossible. - Anonymous",
    "Don’t stop when you’re tired. Stop when you’re done. - Anonymous",
    "Wake up with determination. Go to bed with satisfaction. - Anonymous",
    "Little things make big things happen. - John Wooden",
    "Don’t limit your challenges. Challenge your limits. - Anonymous",
    "When you feel like quitting, remember why you started. - Anonymous",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Hard work beats talent when talent doesn’t work hard. - Tim Notke",
    "Success is the result of preparation, hard work, and learning from failure. - Colin Powell",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "If you want to achieve greatness stop asking for permission. - Anonymous",
    "The secret of getting ahead is getting started. - Mark Twain",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Opportunities don’t happen, you create them. - Chris Grosser",
    "Don’t wait for the perfect moment. Take the moment and make it perfect. - Anonymous",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "If you can dream it, you can do it. - Walt Disney",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Everything you can imagine is real. - Pablo Picasso",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Don’t wait for opportunity. Create it. - Anonymous",
    "It’s never too late to be what you might have been. - George Eliot",
    "Your only limit is your mind. - Anonymous",
    "Push yourself, because no one else is going to do it for you. - Anonymous",
    "The only time you should ever look back is to see how far you’ve come. - Anonymous",
    "The harder the battle, the sweeter the victory. - Les Brown",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Act as if what you do makes a difference. It does. - William James",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "What seems impossible today will one day become your warm-up. - Anonymous",
    "Opportunities don’t happen. You create them. - Chris Grosser",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Everything you can imagine is real. - Pablo Picasso",
    "What we achieve inwardly will change outer reality. - Plutarch",
    "Dream big and dare to fail. - Norman Vaughan",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "If you don’t make mistakes, you’re not working on hard enough problems. And that’s a big mistake. - Frank Wilczek",
    "The best revenge is massive success. - Frank Sinatra",
    "I’ve failed over and over and over again in my life, and that is why I succeed. - Michael Jordan",
    "Success is the result of preparation, hard work, and learning from failure. - Colin Powell",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Anonymous",
    "Don’t stop when you’re tired. Stop when you’re done. - Anonymous",
    "Wake up with determination. Go to bed with satisfaction. - Anonymous",
    "Dream big. Start small. Act now. - Robin Sharma",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Success is how high you bounce when you hit bottom. - George S. Patton",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "If you’re going through hell, keep going. - Winston Churchill",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Your limitation—it’s only your imagination. - Anonymous",
    "Push yourself, because no one else is going to do it for you. - Anonymous",
    "Great things never come from comfort zones. - Anonymous",
    "Dream it. Wish it. Do it. - Anonymous",
    "Success doesn’t just find you. You have to go out and get it. - Anonymous",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Anonymous",
    "Dream bigger. Do bigger. - Anonymous",
    "It’s going to be hard, but hard does not mean impossible. - Anonymous",
    "Don’t stop when you’re tired. Stop when you’re done. - Anonymous",

    // love quotes started

    "Love is composed of a single soul inhabiting two bodies. - Aristotle",
    "To love and be loved is to feel the sun from both sides. - David Viscott",
    "Love is when the other person’s happiness is more important than your own. - H. Jackson Brown Jr.",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams. - Dr. Seuss",
    "Love is a many-splendored thing. - Paul Simon",
    "Where there is love, there is life. - Mahatma Gandhi",
    "Love isn’t something you find. Love is something that finds you. - Loretta Young",
    "In all the world, there is no heart for me like yours. - Maya Angelou",
    "Love is not love which alters when it alteration finds. - William Shakespeare",
    "Love is the only reality, and it is not a mere sentiment. It is the ultimate truth that lies at the heart of creation. - Rabindranath Tagore",
    "True love is not about perfection, it is hidden in flaws. - Anonymous",
    "Love is like the wind, you can’t see it but you can feel it. - Nicholas Sparks",
    "There is only one happiness in this life, to love and be loved. - George Sand",
    "I am yours, don’t give myself back to me. - Rumi",
    "Love is a friendship set to music. - Joseph Campbell",
    "Love is the greatest refreshment in life. - Pablo Picasso",
    "To love is to suffer. To avoid suffering, one must not love. But then one suffers from not loving. - Friedrich Nietzsche",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. - Lao Tzu",
    "Love is the closest thing we have to magic. - Anonymous",
    "Love is an endless act of forgiveness. - Maya Angelou",
    "The best thing to hold onto in life is each other. - Audrey Hepburn",
    "Love is not finding someone to live with; it’s finding someone you can’t imagine living without. - Rafael Ortiz",
    "You don’t love someone because they’re perfect, you love them despite their imperfections. - Jodi Picoult",
    "True love cannot be found where it does not exist, nor can it be denied where it does. - Torquato Tasso",
    "I would rather spend one lifetime with you, than face all the ages of this world alone. - J.R.R. Tolkien",
    "Love isn’t something you find. Love is something that finds you. - Loretta Young",
    "We are shaped and fashioned by what we love. - Johann Wolfgang von Goethe",
    "Love is a great beautifier. - Louisa May Alcott",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "There is no remedy for love but to love more. - Henry David Thoreau",
    "Love is all we have, the only way that each can help the other. - Euripides",
    "The course of true love never did run smooth. - William Shakespeare",
    "Love is the ultimate truth at the heart of all creation. - Rabindranath Tagore",
    "A loving heart is the truest wisdom. - Charles Dickens",
    "Love is a promise, love is a souvenir, once given never forgotten, never let it disappear. - John Lennon",
    "To love oneself is the beginning of a lifelong romance. - Oscar Wilde",
    "Love does not consist in gazing at each other, but in looking outward together in the same direction. - Antoine de Saint-Exupery",
    "In order to be happy oneself, it is necessary to make at least one other person happy. - Theodor Reik",
    "True love is eternal, infinite, and always like itself. - Honore de Balzac",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams. - Dr. Seuss",
    "A loving heart is the truest wisdom. - Charles Dickens",
    "You are my heart, my life, my one and only thought. - Arthur Conan Doyle",
    "If I know what love is, it is because of you. - Hermann Hesse",
    "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day. - Unknown",
    "If I had a flower for every time I thought of you, I could walk through my garden forever. - Alfred Lord Tennyson",
    "Love is like the wind, you can’t see it but you can feel it. - Nicholas Sparks",
    "There is no remedy for love but to love more. - Henry David Thoreau",
    "We loved with a love that was more than love. - Edgar Allan Poe",
    "When I saw you I fell in love, and you smiled because you knew. - Arrigo Boito",
    "Love is a many-splendored thing. - Paul Simon",
    "The best love is the one that makes you a better person, without changing you into someone other than yourself. - Anonymous",
    "Love is not love which alters when it alteration finds. - William Shakespeare",
    "True love is eternal, infinite, and always like itself. - Honore de Balzac",
    "We are shaped and fashioned by what we love. - Johann Wolfgang von Goethe",
    "To love is to suffer. To avoid suffering, one must not love. But then one suffers from not loving. - Friedrich Nietzsche",
    "Love is an endless act of forgiveness. - Maya Angelou",
    "The heart has its reasons of which reason knows nothing. - Blaise Pascal",
    "Love is all we have, the only way that each can help the other. - Euripides",
    "Love is composed of a single soul inhabiting two bodies. - Aristotle",
    "True love is not about perfection, it is hidden in flaws. - Anonymous",
    "The greatest happiness of life is the conviction that we are loved. - Victor Hugo",
    "You don’t love someone because they’re perfect, you love them despite their imperfections. - Jodi Picoult",
    "Love is like the wind, you can’t see it but you can feel it. - Nicholas Sparks",
    "There is only one happiness in this life, to love and be loved. - George Sand",
    "True love cannot be found where it does not exist, nor can it be denied where it does. - Torquato Tasso",
    "The best thing to hold onto in life is each other. - Audrey Hepburn",
    "To love is to suffer. To avoid suffering, one must not love. But then one suffers from not loving. - Friedrich Nietzsche",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "There is no remedy for love but to love more. - Henry David Thoreau",
    "Love is a great beautifier. - Louisa May Alcott",
    "True love is not about perfection, it is hidden in flaws. - Anonymous",
    "Love is the greatest refreshment in life. - Pablo Picasso",
    "To love is to suffer. To avoid suffering, one must not love. But then one suffers from not loving. - Friedrich Nietzsche",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. - Lao Tzu",
    "Love is the closest thing we have to magic. - Anonymous",
    "Love is an endless act of forgiveness. - Maya Angelou",
    "The best thing to hold onto in life is each other. - Audrey Hepburn",
    "Love is not finding someone to live with; it’s finding someone you can’t imagine living without. - Rafael Ortiz",
    "You don’t love someone because they’re perfect, you love them despite their imperfections. - Jodi Picoult",
    "True love cannot be found where it does not exist, nor can it be denied where it does. - Torquato Tasso",
    "I would rather spend one lifetime with you, than face all the ages of this world alone. - J.R.R. Tolkien",

    // spiritual Quotes started

        "The wound is the place where the Light enters you. - Rumi",
        "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it. - Rumi",
        "The quieter you become, the more you can hear. - Ram Dass",
        "When you realize there is nothing lacking, the whole world belongs to you. - Lao Tzu",
        "You are the universe expressing itself as a human for a little while. - Eckhart Tolle",
        "Be yourself; everyone else is already taken. - Oscar Wilde",
        "The universe is full of magical things patiently waiting for our wits to grow sharper. - Eden Phillpotts",
        "When the student is ready, the teacher will appear. - Buddha",
        "In the process of letting go you will lose many things from the past, but you will find yourself. - Deepak Chopra",
        "You cannot step into the same river twice. - Heraclitus",
        "We are not human beings having a spiritual experience. We are spiritual beings having a human experience. - Pierre Teilhard de Chardin",
        "The soul always knows what to do to heal itself. The challenge is to silence the mind. - Caroline Myss",
        "When you let go of the need to control your life, you can finally experience the serenity of being guided. - Anonymous",
        "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. - Charles Darwin",
        "The most beautiful experience we can have is the mysterious. - Albert Einstein",
        "Life is a journey, not a destination. - Ralph Waldo Emerson",
        "The most important thing is to be yourself. Unless you can be a spiritual being. Then, be a spiritual being. - Anonymous",
        "The light you are seeking is within you, not outside. - Buddha",
        "The mind is everything. What you think you become. - Buddha",
        "To love and be loved is to feel the sun from both sides. - David Viscott",
        "The only way to deal with this life meaningfully is to find one's passion, and to pursue it. - Anonymous",
        "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson",
        "Peace comes from within. Do not seek it without. - Buddha",
        "Let go of your attachment to being right, and suddenly your mind is open. - Ralph Marston",
        "I have lived with several Zen masters – all of them cats. - Eckhart Tolle",
        "You are never alone. You are eternally connected with everyone. - Amit Ray",
        "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
        "True love is not about perfection, it is hidden in flaws. - Anonymous",
        "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
        "The highest good is like water. Water gives life to the ten thousand things and does not compete. - Lao Tzu",
        "Not until we are lost do we begin to understand ourselves. - Henry David Thoreau",
        "The kingdom of God is within you. - Jesus Christ",
        "The more I see, the less I know for sure. - John Lennon",
        "You must be the change you wish to see in the world. - Mahatma Gandhi",
        "One of the most spiritual things you can do is embrace your humanity. - Anonymous",
        "Everything has beauty, but not everyone sees it. - Confucius",
        "Our birthdays are feathers in the broad wing of time. - Jean Paul",
        "The way is not in the sky. The way is in the heart. - Buddha",
        "Spirituality is not about being perfect. It’s about living with integrity, openness, and acceptance of the mystery of life. - Anonymous",
        "The mind is everything. What you think you become. - Buddha",
        "There is no way to happiness—happiness is the way. - Thich Nhat Hanh",
        "Look within. Be still. - Ramana Maharshi",
        "The universe is change; our life is what our thoughts make it. - Marcus Aurelius",
        "Silence is the language of God, all else is poor translation. - Rumi",
        "You are not a drop in the ocean. You are the entire ocean in a drop. - Rumi",
        "What you think you become. What you feel you attract. What you imagine you create. - Buddha",
        "You are the universe in ecstatic motion. - Rumi",
        "The greatest wealth is to live content with little. - Plato",
        "When we are no longer able to change a situation, we are challenged to change ourselves. - Viktor Frankl",
        "The more you meditate, the more you will understand that life is so much more than just the things you do. - Anonymous",
        "Meditation is the discovery that the point of life is always arrived at in the immediate moment. - Alan Watts",
        "You are not separate from the universe. The universe is expressing itself through you. - Eckhart Tolle",
        "Life is really simple, but we insist on making it complicated. - Confucius",
        "The quieter you become, the more you can hear. - Ram Dass",
        "There is no need for temples; no need for complicated philosophy. Our own brain, our own heart is our temple; the philosophy is kindness. - Dalai Lama",
        "The mind is everything. What you think you become. - Buddha",
        "Spirituality is not about religion. It’s about understanding the truth. - Anonymous",
        "True love is an act of total surrender. - Anonymous",
        "There is a crack in everything. That’s how the light gets in. - Leonard Cohen",
        "We are not human beings having a spiritual experience. We are spiritual beings having a human experience. - Pierre Teilhard de Chardin",
        "All that we are is the result of what we have thought. - Buddha",
        "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
        "Life is what happens when you’re busy making other plans. - John Lennon",
        "When the mind is quiet, the heart speaks. - Anonymous",
        "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray. - Rumi",
        "Out beyond ideas of wrongdoing and rightdoing, there is a field. I’ll meet you there. - Rumi",
        "Peace is the result of training your mind to process life as it comes. - Anonymous",
        "Gratitude is not only the greatest of virtues, but the parent of all others. - Marcus Tullius Cicero",
        "You have to lose yourself to find yourself. - Eckhart Tolle",
        "Know yourself and you will know the universe. - Anonymous",
        "When you are content to be simply yourself and don’t compare or compete, everybody will respect you. - Lao Tzu",
        "You are the light of the world. - Jesus Christ",
        "Our lives are not determined by what happens to us, but by how we react to what happens. - Anonymous",
        "The law of attraction is always working, whether you believe it or not. - Anonymous",
        "The mind is everything. What you think you become. - Buddha",
        "You are the universe expressing itself as a human for a little while. - Eckhart Tolle",
        "Silence is a source of great strength. - Lao Tzu",
        "Don’t just do something, sit there. - Anonymous",
        "When you meditate, you discover that the point of life is always in the immediate moment. - Alan Watts",
        "Life is a mirror and will reflect back to the thinker what he thinks into it. - Ernest Holmes",
        "The soul becomes dyed with the color of its thoughts. - Marcus Aurelius",
        "We are shaped by our thoughts; we become what we think. - Buddha",
        "True love cannot be found where it does not exist, nor can it be denied where it does. - Torquato Tasso",
        "The energy you give off is the energy you receive. - Anonymous",
        "The purpose of life is not to be happy, but to be useful, honorable, compassionate, and to have made a difference. - Ralph Waldo Emerson",
        "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it. - Rumi",
        "When you let go of the need to control your life, you can finally experience the serenity of being guided. - Anonymous",
        "The essence of life is the expansion of love. - Anonymous",
        "Love is a force that transforms and improves the soul of the world. - Paulo Coelho",
        "You cannot change the past, but you can change your attitude toward it. - Anonymous",
        "It is only with the heart that one can see rightly; what is essential is invisible to the eye. - Antoine de Saint-Exupery",
        "Silence is the language of God, all else is poor translation. - Rumi",
        "When the mind is still, the soul speaks. - Anonymous",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
        "There is no path to happiness: happiness is the path. - Buddha"

]
